### ISSUE TITLE
[Feat] 플레이어 폭탄 생성

### ISSUE THREAD

**Issue by HawoonShin** [KimSesame/Project_M#18]
## 개발요소
플레이어가 스페이스바를 누르면 폭탄을 그 자리에 생성함

## 진행상황
- [ ] 스페이스 입력시 폭탄 생성
- [ ] 생성된 폭탄 위에서 빠져나옴
- [ ] 빠져나온 폭탄으로 다시 올라가지 못함

## 적용방법
폭탄 프리팹을 적용하여 기능 완성

**Comment by KimSesame** [comment]
- 물풍선 생성 방법은 여길 참고해주세요: #6 
- 물풍선을 생성하고 난 후 다시 올라가지 못하게 하는 작업 중 물풍선 쪽에 요청하실 부분 있으면 알려주세요.

**Comment by HawoonShin** [comment]
물풍선 설치 및 폭발에서 구현 완료되어 이슈를 닫습니다.
