### ISSUE TITLE
[Bug] 플레이어가 이동하지 않을 때 항상 윗 방향을 바라봄

### ISSUE THREAD

**Issue by KimSesame** [KimSesame/Project_M#26]
## 1. 버그 / 문제 개요
입력이 없는 상황에서 플레이어가 기존 방향을 유지하지 않고 윗 방향으로 새롭게 설정됩니다.

## 2. 상황 재현
캐릭터 이동 조작을 멈출 시 발생

## 3. 예상 원인
입력이 없을 시 이동벡터를 갱신하지 않아야 하지만 영벡터로 갱신하는 것으로 추측

## 4. 참고자료
![Animation](https://github.com/user-attachments/assets/3bc5a5d2-8079-4f3c-b6b9-613a323a8a5e)

**Comment by HawoonShin** [comment]
# 수정
![Image](https://github.com/user-attachments/assets/9af497c2-975f-422f-9149-8913001ff118)
입력이 있을 때 방향을 회전시키고 없을 때 회전하지 않는 방법으로 코드 수정
