### ISSUE TITLE
[Bug] 캐릭터의 물풍선 속 갇혀있을때도 물풍선을 생성하는 버그

### ISSUE THREAD

**Issue by Geniards** [KimSesame/Project_M#38]
## 1. 버그 / 문제 개요
플레이어가 물풍선에 피격 후 물방울에 갇혀 있는 상태에서 물풍선 생성 버튼을 누를 시 생성이 되는 버그.

## 2. 상황 재현
캐릭터가 물방울에 갇힌 후 물풍선 버튼을 누르면 생성이 되게 동작이 되는 현상이 발생합니다. 

## 3. 예상 원인
물방울에 갇혀 있지만 생성하는 버튼에 대해서 조건을 안걸었기에 해당 동작이 실행되는 듯 합니다.

## 4. 참고자료
![제목 없는 동영상 - Clipchamp로 제작 (13)](https://github.com/user-attachments/assets/521e2d9d-dea6-413a-bbf4-21000340d8d6)

## 5. 구동 환경
운영채제 및 자신의 구동환경 정보 기재
Window / Unity Editor 2021.3.43f1

**Comment by HawoonShin** [comment]
# 버그수정
물방울 안에 들어갔을 때, 설치 스크립트를 활성 비활성하는 방향으로 코드 수정해서 버그 수정했습니다. 
월요일 머지 후 이슈 닫겠습니다.

**Comment by HawoonShin** [comment]
# 수정
![Image](https://github.com/user-attachments/assets/46b039c4-cfef-45a2-a8d4-c10569f5dcdf)
설치 스크립트를 온오프 하는 방식으로 수정하였습니다.
