### ISSUE TITLE
[Bug] 물풍선의 재설치시에 미설치가 되는 버그.

### ISSUE THREAD

**Issue by Geniards** [KimSesame/Project_M#39]
## 1. 버그 / 문제 개요
- 물풍선을 설치시 한번 설치 된 곳에 바로 다시 재설치하려고 하면 설치가 안되는 버그 발생.

## 2. 상황 재현
- 캐릭터가 물풍선을 설치 후 폭발이 일어 난 후 다시 해당 위치에서 물풍선을 설치시 해당 물풍선이 생성이 되지않음. 
1. 캐릭터가 0,0,3에서 물풍선을 설치한다.
2. 물풍선이 동작 후 다시 캐릭터가 0,0,3의 자리에 가서 설치를 시도시 설치가 되지 않는 현상 발생.

## 3. 예상 원인
- 물풍선이 동작 후 pool로 돌아갈시 해당 위치에대해서 리셋이 안된 상태로 진행이 되어서 문제가 발생하는 듯 합니다.
![스크린샷 2024-11-23 194806](https://github.com/user-attachments/assets/c83fa223-4d9b-4eef-8b14-2a3c7b9edc43)

- Physics.OverlapSphere 충돌 검사에 의하여 다시 놓았던 자리에 이미 다른 물풍선이 존재하기에 설치가 안되는 현상이 나타나는 듯합니다.

## 4. 참고자료
![제목 없는 동영상 - Clipchamp로 제작 (15)](https://github.com/user-attachments/assets/8c6613eb-7dac-4e26-bbb6-10d6a143533d)
- 물풍선을 설치 후 해당 물풍선이 pool로 돌아간 후 해당 물풍선의 위치값이 갱신 되어 있는 상태입니다.

![제목 없는 동영상 - Clipchamp로 제작 (16)](https://github.com/user-attachments/assets/93618f76-df5c-4330-97a0-ac6dd3c66e85)
- 해당 자리로 가서 물풍선을 설치하려고 재설치가 불가합니다.
- 위치값을 초기화 후 다시 설치시 해당 자리에 다시 설치가 되는 모습입니다.

## 5. 구동 환경
운영채제 및 자신의 구동환경 정보 기재
Window / Unity Editor 2021.3.43f1

**Comment by KimSesame** [comment]
물풍선 비활성화 시 필드가 아닌 임의의 구역으로 위치를 이동하도록 하여 수정했습니다.
