### ISSUE TITLE
[Feat] 플레이어 이동 구현

### ISSUE THREAD

**Issue by HawoonShin** [KimSesame/Project_M#5]
## 개발요소
플레이어의 기초 이동 구현 및 바라보는 방향으로의 회전을 구현합니다.

## 진행상황
- [x] 플레이어 입력 받기
- [x] 받은 입력으로 이동
- [x] 이동 방향으로의 회전

## 적용방법
플레이어 프리팹에 스크립트를 붙여서 사용합니다. 
네트워크 연동에 관련된 수정이 필요할 수 있습니다.

**Comment by HawoonShin** [comment]
## 추가 진행상황
- [x] 플레이어 이동시 애니메이션 출력
- [x] 플레이어 대각 이동 금지
- [x] 동시 키입력시 진행하던 방향으로 이동

**Comment by KimSesame** [comment]
`PlayerController`에서 아래와 같이 플레이어 이동을 구현하고 있습니다.
> transform.Translate(moveDir.normalized * speed * Time.deltaTime, Space.World);

해당 방법은 벽 오브젝트와 물리적 충돌을 무시하기 때문에 충돌을 고려하는 방법을 사용해서 플레이어 이동을 구현해주세요.
ex.) `Rigidbody`, `CharacterController`

**Comment by HawoonShin** [comment]
리지드 바디를 추가하되 기존과 같이 움직이도록 코드 수정 완료하였습니다.
