### ISSUE TITLE
[Feat] 플레이어 동기화

### ISSUE THREAD

**Issue by HawoonShin** [KimSesame/Project_M#50]
## 개발요소
실제 게임 플레이를 위한 동기화 작업

## 진행상황
- [x] 플레이어 스폰
- [x] 스폰 위치 설정
- [x] 위치 동기화
- [x] 플레이어 색상 변경
- [x] 물방울 상태?
- [x] 애니메이션 동기화?

**Comment by Geniards** [comment]
- 플레이어 스폰위치를 적용하는 방법.
  - 맵 프리펩을 하이라이키창에 배치.
  - 플레이어의 스폰위치 전달에 대하여 SpawnPointManger 스크립트를 불러와서 적용.
  - SpawnPointManger.GetSpawnPoints()를 이용하여 값을 적용.
![스크린샷 2024-11-25 112906](https://github.com/user-attachments/assets/ad0a110a-6b57-4c25-b499-6c4f5e71e323)

**Comment by HawoonShin** [comment]
# 플레이어 스포너
* 스포너 스크립트
![Image](https://github.com/user-attachments/assets/5afd8b1c-fadb-47f6-b9e2-5e4537d96548)
* 테스트 신
![Image](https://github.com/user-attachments/assets/ac04e635-ebd0-473c-abaa-269a43c15db9)

# 참고사항
후에 게임씬 작성시 테스트신에 플레이어 스폰 함수를 불러올 것

**Comment by HawoonShin** [comment]
# 애니메이션 동기화
![Image](https://github.com/user-attachments/assets/506bc7e8-bb8f-4573-928c-19f0fac90864)
다른 클레이언트에서도 플레이어의 애니메이션이 보이도록 동기화 하였습니다

## 적용 방법 
![Image](https://github.com/user-attachments/assets/5c6d3fd8-5abd-458f-8515-9ef8ae9ad494)
포톤 애니메이터 뷰 의 추가 및 각 파라미터의 항목을 Contious로 변경하여 적용

**Comment by HawoonShin** [comment]
# 플레이어 위치 동기화
![Image](https://github.com/user-attachments/assets/8d6cc10d-c645-4c31-a443-9ec4ea769450)
기존 포톤 리지드바디 뷰 사용으로 캐릭터가 회전되지 않던 문제가 있었으나, transfom view로 변경하여 회전까지 적용되도록 수정하였습니다.

**Comment by HawoonShin** [comment]
머지 후 기능들 동기화가 잘 되있음으로 판단하여 이슈 닫습니다.
