### ISSUE TITLE
[Bug] 방(매치메이킹)관련 버그

### ISSUE THREAD

**Issue by YoungsonMan** [KimSesame/Project_M#57]
## 1. 버그 / 문제 개요
* 레디상태 안보이는 버그
    * 서로 레디한게안보임
    * 나갔다와서 방장바꾸면 보임

* 남겨짐 버그
    * 방장이 바뀌고? 시작하면 남겨진다
방 나갔다 들어갔다 하면서 뭔가 방장위임? 그런거 잘안되서?? 시작할떄 돌아가는게 안되는거 같음
1. 방장(A)가 나간다.
2. 방에있던유저(B)가 방장이된다.
3. (A)가 그방에 다시 들어가고 레디한다
4. (B)가 시작을 했는데 (B)는 남겨진다.
5. 인줄알았는데 아니다 뭔가 햇갈린다

## 2. 상황 재현
* 레디상태 안보이는 버그
    * 방에들어와서 레디 하는데 레디된게 (레디폰트가) 안보인다.
    * 레디 하고 나갔다와서 하면 보인다.

## 3. 예상 원인
* 레디상태 안보이는 버그
    * 레디상태 나오는 폰트 & 레디버튼 구성떄문에 나오는 버그같다.
    * 레디버튼이 눌리면 레디버튼 자녀로된 레디버튼 텍스트가 비활성화 되면서
    * 밑에 숨겨진 노란색 레디텍스트가 보이는데 그자리에 레디텍스트도 뜨고 
    * 버튼은 동기화가 안되어있어서 상대방이 레디 버튼은 눌러도 
    * 그 밑의 레디문자는 나오지만 하이어아키 상태에서 버튼은 가만히 있어서 안보이는거 같음.
    * 그런과정에서 본이이 있던 자리에서 레디를 하고나가면 (레디버튼 텍스트)가 비활성화되고
    * 거기서 이제 그자리를 다른 플레이어가 채우면 보이는 듯하다.

* 남겨짐 버그
    * 위에처럼 하면 되는거 같았는데 뭔가 했갈림...
    * 움짤땄는데 보고 참고 해봐야될듯하다
    * 더 실험해본결과 현제 알아낸건
        * A플레이어가 방을 만든다
        * B플레이어가 그 방(A)을 들어간다
        * B플레이어가 그 방을 나간다
        * B플레이어가 방을 만든다 (B)
        * A플레이어가 방(A)을 나가고 (B)방을 들어간다.
        * 레디를하고 B플레이어가 방장이니까 시작을한다
        * B플레이어는 남고 A플레이어만 다음씬(게임)진입을 한다.
        * 정리:
            * 플레이어로 방에 들어간 사람이 나가서 방을 만들어서 시작을 하면
            * 그 플레이어는 남겨진다.
            * Image03 참고
 

## 4. 참고자료
Image01
![241125_Ready LeftAlone_01](https://github.com/user-attachments/assets/2ee9db64-b3d3-4f31-aa66-16aac05cbb82)
레디버튼 관련... -> 자세히보면 1번박스에 플레이어 레디에 뭔가 힐끔힐끔하는게 보임
그래서 레디버튼 구조랑 레디하면 나오는 텍스트를 좀 손보면 동기화 같은거 안하고 되게 할 수도 있을거 같다.

Image02
![241125_Ready LeftAlone_02_worksOK](https://github.com/user-attachments/assets/aecb6cea-f0d0-4b97-97e9-a1c3dbab6027)
남겨지는 버그는 햇갈린다 그냥 위에 개요에 적힌대로 하면 일어나는 버그인줄 알았는데 
되고, 짤처럼 막 나갔다 들어갔다 막 이상하게 하다보면 일어난다.

Image03
![241125_Ready LeftAlone_03](https://github.com/user-attachments/assets/3d89cc1c-7c5a-4327-ba7a-14d43be5523c)

## 5. 구동 환경
운영채제 및 자신의 구동환경 정보 기재
EX) Window / Unity Editor 2021.3.43f1
EX) Window / Build File

**Comment by YoungsonMan** [comment]
![2024-11-27_LeftAloneBugFix](https://github.com/user-attachments/assets/a1cbaa69-f939-496b-a016-dd1c6d912f3d)
StartGame() 함수 
방들어가면서 StartGameAddListner가 됐는데 그상태로 방장되서 시작되서 안되는것
방패널 비활성화시 구독취소를 했어야 했음.

**Comment by YoungsonMan** [comment]
레디관련은 구조를 갈아치움
![Image](https://github.com/user-attachments/assets/f23f839c-423f-4498-a6bc-c26c642b87b3)

**Comment by Geniards** [comment]
확인했습니다.
