### ISSUE TITLE
[Feat] 벽 오브젝트 생성

### ISSUE THREAD

**Issue by Geniards** [KimSesame/Project_M#7]
## 개발요소
- 오브젝트
  - 부서지는 벽 
    - 조각화된 파괴 가능한 오브젝트
      - 오브젝트가 특정 힘이나 충격을 받을 시에 여러 조각으로 분해되고, 각 조각에 폭발력이 적용되어 흩어지는 효과를 구현합니다.
     ![제목 없는 동영상 - Clipchamp로 제작](https://github.com/user-attachments/assets/01a9748f-41e0-43bc-b938-280b81d3548c)

    - 조각들의 Dissolve 효과
      - 분해된 조각들이 특정 시간이 지나면 점진적으로 소멸되도록 소멸 효과를 적용합니다.
     ![제목 없는 동영상 - Clipchamp로 제작 (1)](https://github.com/user-attachments/assets/783d4036-4689-4f33-8c5f-7b3ffb23673e)
    
    - ~~물리적 충돌 감지 및 폭발 효과~~
      - ~~오브젝트에 특정한 충돌이 발생했을 때 파괴가 이루어지도록 구현 합니다.~~

  - 안부서지는 벽
    - 오브젝트에 특정한 충돌 등에 파괴가 이루어지지 않도록 구현합니다.

## 진행상황
- [x] 조각화된 파괴 가능한 오브젝트 생성 및 프리팹 구성
- [x] 폭발력 적용으로 조각들이 흩어지도록 설정
- ~~[ ] 특정 힘을 받았을 시 파괴되도록 충돌 감지 기능 추가~~
- [x] Dissolve 쉐이더를 활용하여 추가적인 소멸 효과를 적용.

## 적용방법
- 사라지게 할 오브젝트에게 ProceduralDestruction스크립트를 부착한다.
  - ProceduralDestruction 스크립트의 FragmentPrefab의 자리에 조각의 프리펩을 넣어준다.
  - ParentContainer부분에 파편이 생성될때 부모로 들어갈 빈오브젝트를 넣어준다.
![스크린샷 2024-11-21 010933](https://github.com/user-attachments/assets/ac04be4c-39a1-45f6-a105-87d6e7efed28)
- ProceduralDestruction스크립트의 DestroyObject()메서드를 호출시 원본 오브젝트가 사라지면서 파편이 랜덤적으로 발사가 된다.

- Dissolve 효과를 적용하려면 사라지게 할 오브젝트에다가 DissolveController스크립트를 부착한다.
  - DissolveShader 부분에 Shader를 적용.
  - Noise Texture에 원하는 noise texture를 넣어준다.
  - 사라질 속도 및 딜레이 시간을 기입한다.
![스크린샷 2024-11-21 011625](https://github.com/user-attachments/assets/e22acaa5-8d2f-4798-ab99-30fe9a559a87)

**Comment by Geniards** [comment]
- 부서지는 벽의 경우 
  - ProceduralDestruction(절차적 파괴)를 이용하여 작은 큐브로 쪼개지듯 구현시도. 
  - 원래라면 Voronoi 알고리즘을 이용하여 진행을 하는것으로 알고 있었지만, 일단은 작은 큐브로의 쪼개짐으로 구현시도. <br>(Voronoi 알고리즘은 추후 로직 개편할때 적용예정.)
  - Dissolve효과에 대해서는 shader부분에 대해서 적용을 진행을 해야할듯 함.

**Comment by KimSesame** [comment]
> ## 진행상황
> - [ ] 특정 힘을 받았을 시 파괴되도록 충돌 감지 기능 추가

파괴되는 로직은 특정 힘이 아닌 물풍선 폭발에 반응하는 인터페이스를 통해 구현해주세요.
해당 인터페이스는 `IWaterBombInteractable`로 상호작용 반응 메소드 `Interact()`를 포함할 예정입니다.

> ##진행상황
> - [ ] Dissolve 쉐이더를 활용하여 추가적인 소멸 효과를 적용.

추가적인 소멸 효과는 후순위로 미루고 다른 파괴 가능한 벽, 아이템 기능 구현 해주시면 감사하겠습니다.

**Comment by Geniards** [comment]
네 알겠습니다. 다시 수정 하도록 하겠습니다.

**Comment by Geniards** [comment]
- 최종 동작영상
  - ProceduralDestruction + Dissolve 효과 적용 모습
![제목 없는 동영상 - Clipchamp로 제작 (2)](https://github.com/user-attachments/assets/bdb68912-e543-4bd6-abed-77fc88804185)

**Comment by KimSesame** [comment]
부서진 잔해에 collider가 존재해 플레이어의 이동에 방해가 되는 상황이 발생할 것 같습니다.
부서진 잔해에는 물리연산이 적용되지 않도록 수정해주시면 감사하겠습니다.

**Comment by Geniards** [comment]
네 알겠습니다. 수정 사항 진행하도록 하겠습니다.

**Comment by Geniards** [comment]
- 부서진 잔해에 대한 수정 내역
  - 잔해에 대해서 collider를 끄거나, isTrigger를 동작시 바닥을 통과하는 현상이 발생합니다.
![제목 없는 동영상 - Clipchamp로 제작 (4)](https://github.com/user-attachments/assets/da8516b3-277a-402d-89a1-dba760b5e81a)


  - 캐릭터와의 물리연산이 동작이 안되게 하도록하여 캐릭터의 tag를 받아와서 해당 tag를 가진 Collider를 가진 물체와의 물리연산을 무시하는 방식으로 진행했습니다.
![스크린샷 2024-11-21 113114](https://github.com/user-attachments/assets/96066d0a-4069-4ca0-af28-a800b7044137)



  - 캐릭터의 Collider를 받아올때 캐릭터가 여럿이 존재하는 경우를 생각하여 List로 캐릭터의 Collider를 받아오면서 캐싱작업을 진행했습니다.
![스크린샷 2024-11-21 112454](https://github.com/user-attachments/assets/891e966b-5b6f-4dcf-a5bb-cd7cb5173cb0)

- 최종적으로 수정한 결과
  - 흰색 큐브 : 부서지는 벽
  - 검은색 큐브 : 안부서지는 벽
  - 흰색 캡슐 : 캐릭터
![제목 없는 동영상 - Clipchamp로 제작 (6)](https://github.com/user-attachments/assets/a8cef268-4af0-45de-984c-35e0b68af74c)
