### ISSUE TITLE
[Feat] 사용 아이템, 능력 아이템 인터페이스 작성

### ISSUE THREAD

**Issue by KimSesame** [KimSesame/Project_M#83]
## 개발요소
- 게임내에서 플레이어가 사용하는 아이템에 대하여 구현합니다.
  - ex) 바늘, 다트 등.
- ~~게임 중 플레이어에게 능력이 부여되는 아이템을 구현합니다.~~
  - ~~ex) 신발, 장갑 등.~~

## 진행상황
- [x] 바늘 아이템 생성.
- [x] 다트 아이템 생성.
- [x] 인벤토리 생성.

**Comment by Geniards** [comment]
- 바늘 아이템 및 다트 아이템 생성시 아이템별 타입으로 나누어서 Active형 타입의 아이템인 경우 인벤토리에 들어가도록 구현하도록 방향을 잡았습니다.
- Active형 아이템이 중복으로 습득하더라도 한개의 아이템만 가지도록 구현예정 입니다.
- 인벤토리가 가득찬 경우에 습득시 이미 습득한 아이템은 삭제 후 새로 습득한 아이템을 우선적으로 인벤토리에 들어가도록 구현.

**Comment by Geniards** [comment]
## 구현 내용
- Active타입으로 생성. 
  ![바늘 아이템 Active형으로 생성](https://github.com/user-attachments/assets/e51d6b63-9479-4822-a2d7-2068e1b915e2)
- [Active형 아이템 습득시 인벤토리로 저장
![Active형 아이템 습득시 인벤토리로 저장](https://github.com/user-attachments/assets/b3a4026f-5617-4ff1-afe1-3e5c5f6cef31)
- Active형 아이템 사용시 인벤토리에서 삭제
![Active형 아이템 사용시 인벤토리에서 삭제](https://github.com/user-attachments/assets/3aa66969-671c-4952-b2ad-b6533f2d20e9)
