### ISSUE TITLE
[Bug] 블럭파괴 안됨 + 물풍선 터지지 않음

### ISSUE THREAD

**Issue by HawoonShin** [KimSesame/Project_M#85]
## 1. 버그 / 문제 개요
얼음 맵 

## 2. 상황 재현
특정 위치에서 물풍선 생성 시 블럭과 물풍선이 일부 플레이어에게 터지지 않는 버그가 발생

## 3. 예상 원인
예상 원인 파악 불가

## 4. 참고자료
* 버그 발생 위치
![image](https://github.com/user-attachments/assets/435425f2-c912-4ab6-b574-0a9a67b57fcf)
* 버그 로그(추정)(해당 버그의 로그인지 의심됨)
![image](https://github.com/user-attachments/assets/15e0da2f-d781-4104-933a-c028a38f1b06)

## 6. 추가 코멘트
원인 발견 및 추가 사항들은 현 이슈탭의 코맨트로 추가 정리가 필요합니다.

**Comment by Geniards** [comment]
## 버그 수정 및 원인
- 해당 부분에 아이템 프리펩이 비어있는 상황이었음을 파악 했습니다.
  - 아이템 생성시에 인덱스가 비어있는 상황이었으므로 범위를 침범했다는 에러 발생하는 상황이었습니다.
![스크린샷 2024-11-27 145133](https://github.com/user-attachments/assets/0624492e-05c9-4520-b129-bd50a44fa674)

- 버그내용 수정상황
![스크린샷 2024-11-28 000438](https://github.com/user-attachments/assets/fdce8973-ad0f-497b-88af-49d449160fd5)
